name: pull test ease

on: [workflow_dispatch]

jobs:
  pull_and_run:
    runs-on: ubuntu-latest
    steps:
    - name: Docker Login
      run: |
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USER }}" --password-stdin

    - name: Pull Docker Image
      run: |
        docker pull "${{ secrets.DOCKER_USER }}/test-bookies"

    - name: Run Docker Container
      run: |
        mkdir -p logs
        docker run --name test-bookies-container -v ${{ runner.workspace }}/logs:/app/logs "${{ secrets.DOCKER_USER }}/test-bookies"

    - name: Copy Network Requests Log from Container
      run: |
        docker cp test-bookies-container:/app/network_requests.json ./network_requests.json

    - name: Save Log as Artifact
      uses: actions/upload-artifact@v4
      with:
        name: network-requests-log
        path: ./network_requests.json

    - name: Copy Screenshots from Container
      run: |
        docker cp test-bookies-container:/app/before.png ./before.png
        docker cp test-bookies-container:/app/img_*.png ./img_*.png

    - name: Save Screenshots as Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: screenshots
        path: ./*.png

    - name: Clean up
      run: |
        docker rm test-bookies-container
