name: run test bookie

on: [workflow_dispatch]
#
jobs:
  pull_and_run:
    runs-on: ubuntu-latest
    steps:
    - name: Docker Login
      run: |
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USER }}" --password-stdin

    - name: Pull Docker Image
      run: |
        docker pull "${{ secrets.DOCKER_USER }}/test-bookies"

    - name: Run Docker Container
      run: |
        mkdir -p logs
        docker run --name test-bookies-container -v ${{ runner.workspace }}/logs:/app/logs "${{ secrets.DOCKER_USER }}/test-bookies"

    - name: Copy match data from container
      run: |
        docker cp test-bookies-container:/app/match_data.json ./match_data.json

        docker cp test-bookies-container:/app/shots ./shots

    - name: upload match data
      uses: actions/upload-artifact@v4
      with:
        name: match-data
        path: match_data.json

    - name: upload screenshots
      uses: actions/upload-artifact@v4
      with:
        name: screenshots
        path: ./shots

    - name: Clean up
      run: |
        docker rm test-bookies-container
