name: Run Docker Command

on:
  workflow_dispatch:
    inputs:
      docker_command:
        description: "Enter the Docker command to run (e.g., ps, images, run hello-world)"
        required: true
        default: "ps"

jobs:
  run-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Run Input Docker Command
        run: |
          echo "Running Docker command: ${{ github.event.inputs.docker_command }}"
          docker ${{ github.event.inputs.docker_command }}
