name: Pull and Run Docker Image

on: [workflow_dispatch]

jobs:
  pull_and_run:
    runs-on: ubuntu-latest
    steps:
    - name: Docker Login
      run: |
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USER }}" --password-stdin

    - name: Pull Docker Image
      run: |
        docker pull "${{ secrets.DOCKER_USER }}/test-app"

    - name: Run Docker Container
      run: |
        docker run --name test-app-container "${{ secrets.DOCKER_USER }}/test-app"
    - name: Copy screenshots from container
      run: |
        docker cp test-app-container:/app/before.png ./before.png
        docker cp test-app-container:/app/after.png ./after.png

    - name: Save screenshots as artifacts
      uses: actions/upload-artifact@v3
      with:
        name: screenshots
        path: ./*.png

    - name: Clean up
      run: |
        docker rm test-app-container
