name: Scrape Supabets

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: dockhercontainer/test-bookies:latest
      volumes:
        - .:/app

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
