name: Scrape Supabets

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: dockhercontainer/test-bookies:latest
      volumes:
        - .:/app

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Create dummy.txt inside /app
        run: |
          mkdir -p /app/dummy.txt

      - name: List files in /app
        run: |
          ls -la /app
      - name: Copy dummy.txt to host system
        run: |
          cp dummy.txt ./dummy.txt
      - name: Upload dummy.txt as artifact
        uses: actions/upload-artifact@v4
        with:
          name: dummy-artifact
          path: ./dummy.txt
